# Generated by Django 6.0.1 on 2026-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargaacademica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='dia',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado')], default='LU', max_length=2),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cargaacademica',
            unique_together={('profesor', 'dia', 'hora_inicio', 'periodo_lectivo')},
        ),
    ]
