# Generated by Django 6.0.1 on 2026-01-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='registroactividad',
            options={'verbose_name': 'Registro de Actividad', 'verbose_name_plural': 'Registros de Actividades'},
        ),
    ]
