# Generated by Django 6.0.1 on 2026-01-30 11:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='dias_gracia_pago',
            field=models.IntegerField(default=15, help_text='Días desde la inscripción antes de entrar en mora', verbose_name='Días de Gracia para Pago'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comprobante_convenio',
            field=models.CharField(blank=True, help_text='Número del documento del convenio firmado', max_length=100, verbose_name='Número de Convenio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='convenio_activo',
            field=models.BooleanField(default=False, help_text='Si tiene convenio, no se bloquea aunque tenga deuda', verbose_name='Convenio de Pago Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_limite_convenio',
            field=models.DateField(blank=True, help_text='Hasta cuándo está vigente el convenio', null=True, verbose_name='Fecha Límite del Convenio'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='precio_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Precio por Crédito'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='prerequisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesores', to='portal.materia', verbose_name='Prerequisito'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Periodo Activo'),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código del Periodo'),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='aula',
            field=models.CharField(max_length=20, verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='codigo_seccion',
            field=models.CharField(max_length=5, verbose_name='Código de Sección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='porcentaje_beca',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Beca'),
        ),
    ]
