# Generated by Django 6.0.1 on 2026-01-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_cargaacademica_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargaacademica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='estudiante',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'estudiante'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='nota_final',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='periodo_lectivo',
            field=models.CharField(default='2026-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_docentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
