# Generated by Django 6.0.1 on 2026-02-01 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_carrera_dias_gracia_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_nota_puesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se Puso la Nota'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_modificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Última Modificación Por'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_puesta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_puestas', to=settings.AUTH_USER_MODEL, verbose_name='Nota Puesta Por'),
        ),
    ]
