# Generated by Django 6.0.1 on 2026-01-20 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_estudiante_materia_alumnos_inscritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroactividad',
            name='alumno',
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.estudiante'),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo',
            field=models.CharField(choices=[('nota', 'Nota'), ('asistencia', 'Asistencia'), ('extra', 'Extra'), ('INSCRIPCION', 'Inscripción')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
