# Generated by Django 6.0.1 on 2026-01-20 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_registroactividad_alumno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroactividad',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Actividad', 'verbose_name_plural': 'Registros de Actividades'},
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='alumnos_inscritos',
            new_name='estudiantes_inscritos',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='alumnos',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('administrativo', 'Personal Administrativo'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='portal.estudiante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='portal.materia'),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='valor',
            field=models.CharField(max_length=50),
        ),
    ]
