# Generated by Django 6.0.1 on 2026-01-20 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_registroactividad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registroactividad',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'INSCRIPCION')), fields=('estudiante', 'materia', 'tipo'), name='unique_inscripcion_estudiante'),
        ),
    ]
